/**
 * Type declaration for the m2cgen-transpiled Random Forest model
 * (randomForestModel.js — auto-generated by model/train_and_transpile.py).
 *
 * @param input 8-element numeric feature vector. STRICT index mapping
 *              (must match Python training preprocessing — see pipeline.md §7):
 *              [0] role_customer        (0/1)
 *              [1] role_moderator       (0/1)
 *              [2] role_admin           (0/1)
 *              [3] resource_sensitivity (LOW=0, MEDIUM=1, HIGH=2)
 *              [4] is_office_hours      (0/1)
 *              [5] record_owner_match   (0/1)
 *              [6] recent_request_count (integer)
 *              [7] failed_attempt_count (integer)
 * @returns 3-element class-probability vector [P(LOW), P(MEDIUM), P(HIGH)]
 *          averaged over the 75 trees. Risk level = argmax.
 */
export declare function score(input: number[]): number[];
